caferma/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django.contrib.auth.models import User
from core.forms import UserUpdateForm, UserForm, CategoryForm, EventForm, ProductForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from core.models import News, Category, Event, Product
from core.views import NewsCreate, NewsUpdate, EventCreate, ProductCreate, ClassificationList
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^usuarios/$', login_required(ListView.as_view(template_name="users.html", model=User,
                                                        paginate_by=20)), name='users'),
    url(r'^agregar-usuario/$', login_required(CreateView.as_view(
        model=User, form_class=UserForm, template_name="user_form.html", success_url='/usuarios/')),
        name='create_user'),
    url(r'^modificar-usuario/(?P<pk>\d+)/$', login_required(UpdateView.as_view(
        model=User, form_class=UserUpdateForm, template_name="user_form.html", success_url='/usuarios/')),
        name='update_user'),
    url(r'^eliminar-usuario/(?P<pk>\d+)/$', login_required(DeleteView.as_view(
        model=User, success_url='/usuarios/')), name='delete_user'),
    url(r'^iniciar-sesion/$', auth_views.login, {'template_name': 'user/login_logout_register/sign-in.html'},
        name='auth_login'),
    url(r'^cerrar-sesion/$', auth_views.logout, {'next_page': '/iniciar-sesion/'},
        name='auth_logout'),
    #Noticias
    url(r'^noticias/$', login_required(ListView.as_view(template_name="news.html", model=News,
                                                        paginate_by=20)), name='news'),
    url(r'^agregar-noticia/$', login_required(NewsCreate.as_view()), name='create_news'),
    url(r'^modificar-noticia/(?P<pk>\d+)/$', login_required(NewsUpdate.as_view()), name='update_news'),
    url(r'^eliminar-noticia/(?P<pk>\d+)/$', login_required(DeleteView.as_view(
        model=News, success_url='/noticias/')), name='delete_news'),
    #Categorias
    url(r'^categorias/$', login_required(ListView.as_view(template_name="categories.html", model=Category,
                                                          paginate_by=20)), name='categories'),
    url(r'^agregar-categoria/$', login_required(CreateView.as_view(
        model=Category, form_class=CategoryForm, template_name="category_form.html", success_url='/categorias/')),
        name='create_category'),
    url(r'^modificar-categoria/(?P<pk>\d+)/$', login_required(UpdateView.as_view(
        model=Category, form_class=CategoryForm, template_name="category_form.html", success_url='/categorias/')),
        name='update_category'),
    url(r'^eliminar-categoria/(?P<pk>\d+)/$', login_required(DeleteView.as_view(
        model=Category, success_url='/categorias/')), name='delete_category'),
    #Eventos
    url(r'^eventos/$', login_required(ListView.as_view(template_name="events.html", model=Event,
                                                       paginate_by=20)), name='events'),
    url(r'^agregar-evento/$', login_required(EventCreate.as_view()), name='create_event'),
    url(r'^modificar-evento/(?P<pk>\d+)/$', login_required(UpdateView.as_view(
        model=Event, form_class=EventForm, template_name="event_form.html", success_url='/eventos/')),
        name='update_event'),
    url(r'^eliminar-evento/(?P<pk>\d+)/$', login_required(DeleteView.as_view(
        model=Event, success_url='/eventos/')), name='delete_event'),
    #Productos
    url(r'^productos/$', login_required(ListView.as_view(template_name="products.html", model=Product,
                                        paginate_by=20)), name='products'),
    url(r'^agregar-producto/$', login_required(ProductCreate.as_view()), name='create_product'),
    url(r'^modificar-producto/(?P<pk>\d+)/$', login_required(UpdateView.as_view(
        model=Product, form_class=ProductForm, template_name="product_form.html", success_url='/productos/')),
        name='update_product'),
    url(r'^eliminar-producto/(?P<pk>\d+)/$', login_required(DeleteView.as_view(
        model=Product, success_url='/productos/')), name='delete_product'),
    url(r'^productos/clasificaciones/$', login_required(ClassificationList.as_view()), name='classifications'),
    #Clasificaciones
    url(r'^agregar-clasificacion/$', 'core.views.add_classification', name='add_classification'),
    url(r'^modificar-clasificacion/(?P<pk>\d+)/$', 'core.views.save_classification', name='save_classification'),
    url(r'^eliminar-clasificacion/(?P<pk>\d+)/$', 'core.views.delete_classification', name='delete_classification'),
    url(r'^sincronizar-clasificacion/$', 'core.views.synchronize_classification', name='synchronize_classification'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^summernote/', include('django_summernote.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User, Permission
from core.models import News, Category, Event, Product, Classification
from django_summernote.widgets import SummernoteWidget


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    user_permissions = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=Permission.objects.filter(
            content_type_id__in=[4, 7, 8, 9, 10, 11, 12]), label="Permisos de usuario", required=False,)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name', 'is_active', 'user_permissions')

    def save(self, commit=False):
        # Save the provided password in hashed format
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    user_permissions = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=Permission.objects.filter(
            content_type_id__in=[4, 7, 8, 9, 10, 11, 12]), label="Permisos de usuario", required=False,)

    class Meta:
        model = User
        # Add all the fields you want a user to change
        fields = ('username', 'email', 'first_name', 'last_name', 'is_active', 'user_permissions')


#noticias
class NewsForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=Category.objects.all(),
        label="Categorías", required=False,)
    body = forms.CharField(widget=SummernoteWidget(), required=True, label='Cuerpo (*)')
    video = forms.CharField(required=False, help_text='URL de YouTube: ejm. https://youtu.be/m6uc8AinCZA')

    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)

        self.fields['title'] = forms.CharField(required=True, label='Título (*)')
        self.fields['is_published'].label = 'Publicar'
        self.fields['is_published'].required = False
        self.fields['image'].label = 'Imagen'
        self.fields['image'].required = False

    class Meta:
        model = News
        fields = ('title', 'body', 'is_published', 'image', 'video', 'categories')


class CategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)

        self.fields['name'].label = 'Nombre (*)'

    class Meta:
        model = Category
        fields = ('name', )


class EventForm(forms.ModelForm):
    information = forms.CharField(widget=SummernoteWidget(), required=True, label='Descripción (*)')
    start_time = forms.DateTimeField(widget=forms.DateTimeInput(format='%d-%m-%Y %H:%M'),
                                     input_formats=('%d-%m-%Y %H:%M',),
                                     required=False, label='Hora de inicio')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Nombre'
        self.fields['is_published'].label = 'Publicar'
        self.fields['is_published'].required = False
        self.fields['address'].label = 'Dirección'
        self.fields['address'].required = False
        self.fields['image'].label = 'Imagen'
        self.fields['image'].required = False

    class Meta:
        model = Event
        fields = ('name', 'information', 'address', 'image', 'is_published', 'start_time',)


class ProductForm(forms.ModelForm):
    body = forms.CharField(widget=SummernoteWidget(), required=True, label='Cuerpo (*)')
    description = forms.CharField(widget=forms.Textarea(), label='Descripción (*)')
    classifications = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=Classification.objects.all(),
        label="Clasificación", required=False,)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Nombre (*)'
        self.fields['logo'].required = False
        self.fields['logo'].label = 'Imagen'

    class Meta:
        model = Product
        fields = ('name', 'logo', 'description', 'body', 'classifications')


class ClassificationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ClassificationForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

    class Meta:
        model = Classification
        fields = ('name', 'description', 'image')

templates/admin.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Administración</title>
</head>
<body>

</body>
</html>

templates/categories.html
{% extends "base_admin.html" %}
{% block title %} Categorías {% endblock title %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Lista de categorías
    </h3>

    <form class="form-horizontal" action="{% url 'create_category' %}" method="post" role="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="name" class="col-sm-4 control-label">Nueva categoría: </label>
            <div class="col-sm-5">
                <input required type="text" class="form-control" id="name" name="name" placeholder="Ingrese un nombre">
            </div>
            <div class="col-sm-2">
                <input type="submit" class="form-control" value="Crear">
            </div>
        </div>

    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for category in object_list %}
            <tr>
                <td>{{ category.name }}</td>
                <td>
                    <div class="content-box content-style2 small">
                        <a href="{% url 'update_category' category.id %}" class="btn btn-sm btn-blue">Editar</a>
                        <a href="{% url 'delete_category' category.id %}" class="btn btn-sm btn-red">Eliminar</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/usuarios?page={{ page_obj.previous_page_number }}"><strong>Anterior</strong></a>
                {% endif %}
                <span class="page-current">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/usuarios?page={{ page_obj.next_page_number }}"><strong>Siguiente</strong></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</div>
{% endblock content %}

templates/category_form.html
{% extends "base_admin.html" %}
{% block title %} Formulario de categorías {% endblock title %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Categoría
    </h3>
    <p class="body_paragraph contact-paragraph">
        Ingrese todos los campos obligatorios (*)
    </p>

    <form class="form-wrapper" id="contact-form" method="post" role="form" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <div class="col-md-2 col-sm-2 col-lg-offset-3">
                {% if object %}
                    <input type="submit" value="Guardar" class="btn btn-lg" />
                {% else %}
                    <input type="submit" value="Crear" class="btn btn-lg" />
                {% endif %}
            </div>
            <div class="col-md-2 col-sm-2">
                <a href="{% url 'categories' %}" class="btn btn-default">Salir</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

templates/classification.html
{% extends "base_admin.html" %}
{% block title %} Clasificaciones {% endblock title %}
{% block styles %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.nestable.css">
{% endblock styles %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Lista de Clasificaciones
    </h3>

    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <button id="save_classifications" class="btn btn-default">Guardar cambios</button>
            </div>

            <div class="dd" id="nestable">
                <ol class="dd-list outer">
                    {% for node in object_list %}
                        {%include "tree_view_template.html" %}
                    {% endfor %}
                </ol>
            </div>

            <div class="m-t-md"><br/>
                <textarea class="form-control" id="nestable-output"></textarea>
            </div>
        </div>
        <div class="col-sm-4">
            <h3>Nueva clasificación: </h3>
            <form id="form_classification" class="form-wrapper form-horizontal" method="post" role="form" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="preview-list"></div>
                <div class="form-group">
                    <input type="text" class="form-control" name="name" id="name" placeholder="Ingrese un nombre">
                </div>
                <div class="form-group">
                    <textarea id="description" name="description" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <span class="js-fileapi-wrapper" style="position: relative;">
                        <input id="user-files" type="file" accept=".jpg,.jpeg,.gif"/>
                    </span>
                </div>
                <div class="form-group">
                    <button id="add_classification" class="btn btn-default">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.nestable.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/app/general.js"></script>
    <script>var FileAPI = { debug: false, pingUrl: false }</script>
	<script src="{{ STATIC_URL }}js/FileAPI/FileAPI.min.js"></script>
	<script src="{{ STATIC_URL }}js/FileAPI/FileAPI.id3.js"></script>
	<script src="{{ STATIC_URL }}js/FileAPI/FileAPI.exif.js"></script>

    <script>
        $(document).ready(function(){
            var json_classification = null;
            var name = $("#name"),
                description = $("#description"),
                user_files = $("#user-files");
            var input = document.getElementById('user-files');
            var previewNode = document.getElementById('preview-list');
            var imageList = null;
            var requestSent = false;
            var updateOutput = function (e) {
                var list = e.length ? e : $(e.target),
                     output = list.data('output');
                if (window.JSON) {
                    output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
                    json_classification = window.JSON.stringify(list.nestable('serialize'));
                } else {
                    output.val('JSON browser support required for this demo.');
                }
            };
            //initial
            name.val('');
            description.val('');
            user_files.val('');
            // activate Nestable for list 1
            $('#nestable').nestable({group: 1}).on('change', updateOutput);
            // output initial serialised data
            updateOutput($('#nestable').data('output', $('#nestable-output')));
            $('#add_classification').click(function (e) {
                e.preventDefault();
                if(name.val() != ""){
                    if(!requestSent) {
                        requestSent = true;
                        FileAPI.upload({
                            url: "/agregar-clasificacion/",
                            data: {
                                'name': $('#name').val(),
                                'description': $('#description').val()
                            },
                            headers: { "X-CSRFToken": $('input[name="csrfmiddlewaretoken"]').prop('value') },
                            files: {
                                image: imageList
                            },
                            imageTransform: {
                                maxWidth:  1024,
                                maxHeight: 768
                            },
                            imageAutoOrientation: true,
                            progress: function (evt){    // (flash, html5)
                                var percent = evt.loaded/evt.total*100;
                                console.log('progres', percent);
                            },
                            complete: function (err, xhr){
                                requestSent = false;
                                if(!err){
                                    var obj = window.JSON.parse(xhr.responseText);
                                    var li = $('<li/>', {
                                        'class': 'dd-item dd3-item',
                                        'data-id': obj.id
                                    });
                                    $('<div/>', {
                                        'class': 'dd-handle dd3-handle',
                                        'text': 'Drag'
                                    }).appendTo(li);
                                    $('<div/>', {
                                        'class': 'dd3-content',
                                        'name': obj.id,
                                        'text': name.val()
                                    }).appendTo(li);
                                    $('ol.outer').append(li);
                                    //Limpiar
                                    description.val('');
                                    name.val('');
                                    user_files.val('');
                                    previewNode.innerHTML = "";
                                    updateOutput($('#nestable').data('output', $('#nestable-output')));
                                }
                            }
                        });
                    }
                }
            });
            $('#save_classifications').click(function (e) {
                e.preventDefault();
                if(json_classification != null){
                    if(!requestSent) {
                        requestSent = true;
                        $.ajax({
                            url: "/sincronizar-clasificacion/",
                            method: "POST",
                            data: { data : json_classification },
                            dataType: "json"
                        }).done(function( data ) {
                            console.log(data);
                        }).complete(function(){
                            requestSent = false;
                        });
                    }
                }
            });

            FileAPI.event.on(input, 'change', function (evt){
                var files = FileAPI.getFiles(evt.target); // or FileAPI.getFiles(evt)
                // filtering
                FileAPI.filterFiles(files, function (file, info){
                    if( /image/.test(file.type) && info ){
                        return  info.width >= 320 && info.height >= 240;
                    }
                    else {
                        return  file.size > 128;
                    }
                }, function (fileList, ignor){
                    if( ignor.length ){
                        user_files.val('');
                        alert('El archivo es muy pequeño debe ser mayor a 320px x 240px');
                        return false;
                    }

                    if( !fileList.length ){
                        return false;
                    }

                    // do preview
                    imageList = FileAPI.filter(fileList, function (file){ return /image/.test(file.type); })[0];
                    FileAPI.Image(imageList)
                        .preview(100, 120)
                        .get(function (err, image){
                            if( err ){
                                alert('Error al cargar la imagen...');// ...
                            }
                            else {
                                previewNode.innerHTML = "";
                                previewNode.appendChild(image);
                            }
                        });
                });
            });
        });
    </script>
{% endblock %}

templates/event_form.html
{% extends "base_admin.html" %}
{% block title %} Formulario de eventos {% endblock title %}
{% block styles %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-datetimepicker.min.css">
{% endblock styles %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Eventos
    </h3>
    <p class="body_paragraph contact-paragraph">
        Ingrese todos los campos obligatorios (*)
    </p>

    <form class="form-wrapper" id="contact-form" method="post" role="form" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <div class="col-md-2 col-sm-2 col-lg-offset-3">
                {% if object %}
                    <input type="submit" value="Guardar" class="btn btn-lg" />
                {% else %}
                    <input type="submit" value="Crear" class="btn btn-lg" />
                {% endif %}
            </div>
            <div class="col-md-2 col-sm-2">
                <a href="{% url 'events' %}" class="btn btn-default">Salir</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-datetimepicker.min.js"></script>
    <script type="application/javascript">
        $(document).ready(function(){
            $("#id_start_time").datetimepicker(
                {
                    language: 'es', weekStart: 1, todayBtn: 1, autoclose: 1,
                    todayHighlight: 1, startView: 2, forceParse: 0, showMeridian: 1,
                    format: 'dd-mm-yyyy hh:ii'
                }
            );
        });
    </script>
{% endblock scripts %}

templates/events.html
{% extends "base_admin.html" %}
{% block title %} Eventos {% endblock title %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Lista de eventos
    </h3>

    <table class="table">
        <thead>
            <tr>
                <th>Fecha de registro</th>
                <th>Título</th>
                <th>Publicado</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for event in object_list %}
            <tr>
                <td>{{ event.creation_time }}</td>
                <td>{{ event.name }}</td>
                <td>{{ event.is_published }}</td>
                <td>
                    <div class="content-box content-style2 small">
                        <a href="{% url 'update_event' event.id %}" class="btn btn-sm btn-blue">Editar</a>
                        <a href="{% url 'delete_event' event.id %}" class="btn btn-sm btn-red">Eliminar</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/eventos?page={{ page_obj.previous_page_number }}"><strong>Anterior</strong></a>
                {% endif %}
                <span class="page-current">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/eventos?page={{ page_obj.next_page_number }}"><strong>Siguiente</strong></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</div>
{% endblock content %}

templates/news.html
{% extends "base_admin.html" %}
{% block title %} Noticias {% endblock title %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Lista de noticias
    </h3>

    <table class="table">
        <thead>
            <tr>
                <th>Fecha de registro</th>
                <th>Título</th>
                <th>Publicado</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for new in object_list %}
            <tr>
                <td>{{ new.creation_time }}</td>
                <td>{{ new.title }}</td>
                <td>{{ new.is_published }}</td>
                <td>
                    <div class="content-box content-style2 small">
                        <a href="{% url 'update_news' new.id %}" class="btn btn-sm btn-blue">Editar</a>
                        <a href="{% url 'delete_news' new.id %}" class="btn btn-sm btn-red">Eliminar</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/noticias?page={{ page_obj.previous_page_number }}"><strong>Anterior</strong></a>
                {% endif %}
                <span class="page-current">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/noticias?page={{ page_obj.next_page_number }}"><strong>Siguiente</strong></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</div>
{% endblock content %}

templates/news_form.html
{% extends "base_admin.html" %}
{% block title %} Formulario de noticias {% endblock title %}
{% block styles %}
    <style>
        #tags_section .tag{
            display: block;
            float: left;
            padding: 0 10px 0 10px;
            border-radius: 10px;
            line-height: 23px;
            position: relative;
            font-size: 11px;
            margin: 0px 10px 10px 0px;
            background-color: #f2f2f2;
        }
        #tags_section .tag a:hover {
            color: #279fbb;
            font-weight: bold;
            text-decoration: none;
        }
        #tags_section .tag input[type="checkbox"]{
            display: none;
        }
    </style>
{% endblock styles %}
{% block content %}
<div class="contact-body">
    <h3 class="h3-body-title">
        Noticias
    </h3>
    <p class="body_paragraph contact-paragraph">
        Ingrese todos los campos obligatorios (*)
    </p>

    <form class="form-wrapper form-horizontal" id="contact-form" method="post" role="form" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p|safe }}
        <label>Tags relacionados:</label>
        <div class="form-group">
            <div class="col-sm-8">
                <div class="input-group col-xs-11">
                    <input type="text" class="input-sm" id="new_tag" name="new_tag"/>
                    <div class="input-group-btn">
                        <button class="btn btn-default btn-sm" id="add_tag">Agregar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" id="tags_section">
            {% if object %}
                {% for tag in object.tags.all %}
                    <div class="tag">
                        <input checked type="checkbox" name="tags" value="{{ tag.name }}">{{ tag.name }}
                        <a href="javascript:void(0)">
                            <i class="icon-forbidden"></i>
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="row">
            <div class="col-md-2 col-sm-2 col-lg-offset-3">
                {% if object %}
                    <input type="submit" value="Guardar" class="btn btn-lg" />
                {% else %}
                    <input type="submit" value="Crear" class="btn btn-lg" />
                {% endif %}
            </div>
            <div class="col-md-2 col-sm-2">
                <a href="{% url 'news' %}" class="btn btn-default">Salir</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function(){
            var new_tag = $("#new_tag");
            var tags_content = $("#tags_section");
            $("#add_tag").click(function(e){
                e.preventDefault();
                if(new_tag.val() != ""){
                    var div = $('<div/>', {
                        'class':'tag',
                        'text': new_tag.val()+' '
                    });
                    var input = $('<input/>', {
                        'checked':'checked',
                        'type':'checkbox',
                        'name':'tags',
                        'value':new_tag.val()
                    }).appendTo(div);
                    var a = $('<a/>', {'href':'javascript:void(0)'});
                    var i = $('<i/>', {'class': 'icon-forbidden'}).appendTo(a);
                    a.appendTo(div);
                    div.appendTo(tags_content);
                    new_tag.val("");
                    new_tag.focus();
                }
            });
            $('#tags_section').on('click', 'a', function(e){
                var _this = $(this);
                _this.parent('.tag').remove();
            });
        });
    </script>
{% endblock scripts %}

templates/tree_view_template.html
<li class="dd-item dd3-item" data-id="{{ node.id }}">
    <div class="dd-handle dd3-handle">Drag</div>
    <div class="dd3-content" name="{{ node.id }}">{{ node.name }}</div>
    {%if node.children.all|length > 0 %}
        <ol class="dd-list">
         {%for ch in node.children.all %}
              {%with node=ch template_name="tree_view_template.html" %}
                   {%include template_name %}
              {%endwith%}
         {%endfor%}
         </ol>
    {%endif%}
</li>